{{- if and .Values.passwordUpdateJob.enabled (not .Values.auth.existingSecret) }}
{{- $fullName := include "mysql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-new-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: password-update
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  {{- if .Values.auth.rootPassword }}
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- else }}
  {{- fail "auth.rootPassword is required when passwordUpdateJob is enabled" }}
  {{- end }}
  {{- if .Values.auth.username }}
    {{- if .Values.auth.password }}
  mysql-password: {{ .Values.auth.password | b64enc | quote }}
    {{- else }}
    {{- fail "auth.password is required when passwordUpdateJob is enabled and auth.username is set" }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.architecture "replication" }}
    {{- if .Values.auth.replicationPassword }}
  mysql-replication-password: {{ .Values.auth.replicationPassword | b64enc | quote }}
    {{- else }}
    {{- fail "auth.replicationPassword is required when passwordUpdateJob is enabled and architecture is replication" }}
    {{- end }}
  {{- end }}
{{- end }}