apiVersion: v2
name: mysql
description: A Helm chart for MySQL using official Docker images
type: application
version: 1.0.0
appVersion: "v9.4.0"
keywords:
  - mysql
  - database
  - sql
home: https://www.mysql.com/
sources:
  - https://github.com/mysql/mysql-server
  - https://hub.docker.com/_/mysql
maintainers:
  - name: Kostiantyn Soloviov
    email: support@webspellchecker.net
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release with official MySQL images